m2gi-davilori/ecom

src/main/java/com/m2gi/ecom/config/SecurityConfiguration.java, src/main/webapp/app/app.module.ts, src/main/webapp/app/components/components-routing.module.ts, src/main/webapp/app/components/products/list/products.component.html, src/main/webapp/app/components/products/list/products.component.spec.ts, src/main/webapp/app/components/products/list/products.component.ts, src/main/webapp/app/components/products/products.module.ts, src/main/webapp/app/components/products/route/products-routing.module.ts, src/main/webapp/app/layouts/navbar/navbar.component.html, src/main/webapp/i18n/en/global.json, src/main/webapp/i18n/fr/global.json
-Ajout d'un bouton de navigation "Produits" redirigeant vers la page "/products".
-Ajout d'une nouvelle page qui liste tous les produits de la base de données avec comme chemin d'accès "/products" ainsi qu'un module général pour les future composants à créer, un module pour la page en question et un fichier de routage.
-L'accès à la liste des produits ne nécessite pas que l'utilisateur soit authentifié.
=> Feature 36: Afficher une version basique des produits

src/main/webapp/app/components/cart/list/cart.component.html, src/main/webapp/app/components/cart/list/cart.component.ts
Ajout du prix total du panier dans de cart.component.html
Ajout d'une méthode de calcul (parcours du panier) pour trouver le prix total + mise en forme du résultat (espace entre 3 chiffre : 2 538 878 952 € au lieu de 2538878952 €)
=> Ajout du prix total du panier dans de cart.component.html

src/main/java/com/m2gi/ecom/service/CartService.java, src/main/java/com/m2gi/ecom/web/rest/CartResource.java, src/main/webapp/app/components/cart/service/cart.service.ts, src/main/webapp/app/components/products/list/products.component.html, src/main/webapp/app/components/products/list/products.component.ts, src/main/webapp/app/config/font-awesome-icons.ts
Ajout du bouton de gestion de quantité "- q +" pour un produit dans la page Products lorsque l'utilisateur est connecté et que le porduit en question est dans le panier.
Ajout d'un "PatchMapping" dans le controller rest pour mettre à jours la quantity d'un ProductCart
Ajout d'un service dans le cartService du component pour appeler le controller rest avec un RequestParam
=> Feature 47

src/main/java/com/m2gi/ecom/service/ProductCartService.java, src/main/java/com/m2gi/ecom/service/impl/ProductCartServiceImpl.java, src/main/java/com/m2gi/ecom/web/rest/CartResource.java, src/main/webapp/app/components/cart/list/cart.component.html, src/main/webapp/app/components/cart/list/cart.component.ts, src/main/webapp/app/components/cart/service/cart.service.ts, src/main/webapp/app/components/products/list/products.component.html, src/main/webapp/app/components/products/list/products.component.ts
Ajout du bouton de gestion de quantité "- q +" pour un produit dans la page Cart
Ajout d'un "PatchMapping" dans le controller rest pour mettre à jours la quantity du ProductCart
Ajout d'un service dans le cartService du component pour appeler le controller rest avec un RequestParam
(Feature bloqué par la feature 44)
=> Feature 24

src/main/java/com/m2gi/ecom/repository/ProductCartRepository.java, src/main/java/com/m2gi/ecom/service/impl/ProductCartServiceImpl.java, src/main/java/com/m2gi/ecom/web/rest/CartResource.java, src/main/resources/.h2.server.properties, src/main/resources/config/application-dev.yml, src/main/webapp/app/components/cart/list/cart.component.html, src/main/webapp/app/components/cart/list/cart.component.ts, src/main/webapp/app/components/cart/service/cart.service.ts, src/main/webapp/app/components/payment/list/payment.component.ts, src/main/webapp/app/components/products/list/products.component.ts, src/main/webapp/app/entities/cart/cart.model.ts
-Ajout du bouton de suppression depuis la page "Panier".
-Dans la page "Panier" et la page "Produits": Automatiquement retirer un article du panier quand la quantité est mise à 0.
=> Feature-22: Ajouter un bouton pour retirer un article du panier.

src/main/webapp/content/css/ecom.css
Augmentation de l'espace entre le texte et les tags
=> Feature 84

src/main/webapp/app/components/products/list/products.component.html, src/main/webapp/app/layouts/navbar/navbar.component.html, src/main/webapp/app/layouts/navbar/navbar.component.ts, src/main/webapp/content/css/ecom.css
Mettre à jour l'affichage du bouton profil et panier lors qu'on est dans les pages concernés
Correction d'une erreur de syntaxe angular
Mise en commentaire la gestion de langue
=> Feature 85

src/main/webapp/app/layouts/navbar/navbar.component.html, src/main/webapp/content/css/ecom.css
Mise en place du CSS de la popup profil selon la maquette
=> Feature 86

src/main/webapp/app/components/cart/list/cart.component.ts, src/main/webapp/app/components/cart/service/cart.service.ts, src/main/webapp/app/components/products/list/products.component.ts, src/main/webapp/app/entities/cart/cart.model.ts, src/main/webapp/app/layouts/navbar/navbar.component.html, src/main/webapp/app/layouts/navbar/navbar.component.scss, src/main/webapp/app/layouts/navbar/navbar.component.ts
Feature 14: Ajouter une notification indiquant le nombre d'items dans le panier.
ajout d'un attribut nbItems dans CartService qui permet de récupérer le nombre d'item dans le panier.
Cet attribut et modifier à chaque action sur le panier dans les composantes (Cart et Products)
=> Feature 14

src/main/java/com/m2gi/ecom/domain/Product.java, src/main/webapp/app/components/products/list/products.component.html, src/main/webapp/app/entities/cart/cart.model.ts, src/main/webapp/content/css/ecom.css
CSS d'un produit en promotion
- Changement du prix
- Ajout d'un bandeau du pourcentage de la promo
=> Feature 39

src/main/webapp/app/components/products/list/products.component.ts
Modification de la methode "addToCart" dans ProductsComponent, afin de verifier si on est connecte avant d'ajouter un produit au panier, si on n'est pas connecte on sera rediriger vers la page "/login"
=> feature-87: Demander la connexion lors de l'ajout d'un produit au panier

src/test/java/com/m2gi/ecom/web/rest/OrderResourceIT.java, src/test/java/com/m2gi/ecom/web/rest/ProductResourceIT.java
Il y avait 7 problèmes: 3 erreurs et 4 failures, ça a été corrigé.
=> Feature-89: Correction des problèmes de tests

src/main/webapp/app/components/payment/display/payment.component.html, src/main/webapp/app/components/reusableComponents/product-card/product-card.component.ts, src/main/webapp/content/css/ecom.css, src/main/webapp/i18n/en/payment.json, src/main/webapp/i18n/fr/payment.json
Mise en place du CSS de la page paiement selon la maquette Figma
=> Feature 82

src/main/webapp/app/layouts/navbar/navbar.component.html, src/main/webapp/content/css/ecom.css
Mise à jour des couleurs CSS et optimisation du CSS de la navbar
=> Feature 88

src/main/webapp/app/components/components-routing.module.ts, src/main/webapp/app/components/favorites/display/favorites.component.html, src/main/webapp/app/components/favorites/display/favorites.component.spec.ts, src/main/webapp/app/components/favorites/display/favorites.component.ts, src/main/webapp/app/components/favorites/favorites.module.ts, src/main/webapp/app/components/favorites/route/favorites-routing.module.ts, src/main/webapp/app/components/products/products.module.ts, src/main/webapp/app/layouts/navbar/navbar.component.html, src/main/webapp/i18n/en/product.json, src/main/webapp/i18n/fr/product.json
Creation de la composante **FavoritesComponent** qui appel **ListProductComponent** pour afficher les produit Favoris
l'URL pour la page des favoris est "/account/favorites"
**FavoritesComponent** recupere les produits de service **ProductService** (l'attribut _listFavorites_)
=> Feature 74: Consulter les favoris

src/main/webapp/app/app.module.ts, src/main/webapp/app/components/categories/display/categories.component.html, src/main/webapp/app/components/categories/display/categories.component.ts, src/main/webapp/app/components/products/display/products.component.html, src/main/webapp/app/components/products/products.module.ts, src/main/webapp/app/layouts/main/main.component.html, src/main/webapp/app/layouts/main/main.component.ts, src/main/webapp/content/css/ecom.css
Changement de la taille des boutons de fin de page (voir panier, passer au paiement, etc...)
Changement de la taille du titre et soulignement dynamique selon sa taille
Changement d'emplacement de l'utilisation du composant categories
Alignement et amélioration de l'affichage des catégories selon la maquette Figma :
- Changement de la couleur par defaut
- Suppression des boutons de dropdown lorsque ce n'est pas necessaire
- Taille du premier parents plus grand que les enfants
- Changement de la couleur selon la categorie cliquée
- Ajout d'un point pour les catégories sans enfants
=> Feature 95

src/main/webapp/app/components/cart/display/cart.component.spec.ts, src/main/webapp/app/components/payment/display/payment.component.spec.ts, src/main/webapp/app/components/products/display/products.component.spec.ts, src/main/webapp/app/components/reusableComponents/list-product/list-product.component.spec.ts, src/main/webapp/app/components/reusableComponents/product-card/product-card.component.spec.ts, src/main/webapp/app/components/reusableComponents/product-line/product-line.component.spec.ts
-Mise en commentaire des fichiers de tests non générés par JHipster (côté front) afin qu'ils ne posent pas problème lors du build.
=> Feature-94: Corriger les tests qui échouent côté front.

src/main/java/com/m2gi/ecom/config/SecurityConfiguration.java, src/main/webapp/app/components/products/display/products.component.ts, src/main/webapp/app/components/reusableComponents/list-product/list-product.component.ts, src/main/webapp/app/components/reusableComponents/product-card/product-card.component.html, src/main/webapp/app/components/reusableComponents/product-card/product-card.component.ts, src/main/webapp/app/components/services/promotion.service.ts
Back-end :
Dans SecurityConfiguration ajout de **.antMatchers("/api/promotions").permitAll()**
Utilisation de **getAllPromotions** dans PromotionResource à partir de Front
Front-end :
Ajout de service **PromotionService** pour gérer tout ce qui est promotion et stockage des promotions dans l'attribut _promotions_
Dans product-card HTML on appelle this.promotionService.getPromotion(product) qui affiche la promotion selon son type PERCENTAGE ou FIX
Dans la page d'accueil on appel getProductsPromotion de promotionService pour afficher que les produits en promo!
=> Feature 78: Afficher les produits en promotion dans la page d'accueil

src/main/webapp/app/components/reusableComponents/product-card/product-card.component.html, src/main/webapp/content/css/ecom.css
Ajout de la condition (this.product.quantity === 0) dans ProductCardComponent HTML 
Modification ecom.css
=> feature-66: Indiquer qu'un produit est en rupture de stock

src/main/java/com/m2gi/ecom/service/CartService.java, src/main/java/com/m2gi/ecom/service/impl/CartServiceImpl.java, src/main/java/com/m2gi/ecom/service/impl/OrderServiceImpl.java, src/main/java/com/m2gi/ecom/web/rest/CartResource.java, src/main/webapp/app/components/payment/display/payment.component.ts
-Migration d'une gestion de stock pessimiste vers une gestion optimiste. 
-Redirection 2 pages en arrière (donc logiquement la liste des produits) après création d'une commande en attendant de rediriger vers l'historique des commandes.
=> Feature-97: Gestion de stock optimiste.

package-lock.json, src/main/java/com/m2gi/ecom/service/impl/CartServiceImpl.java, src/main/webapp/app/components/reusableComponents/product-card/product-card.component.html, src/main/webapp/app/components/reusableComponents/product-line/product-line.component.html, src/main/webapp/app/components/services/cart.service.ts, src/main/webapp/content/css/ecom.css, src/main/webapp/i18n/en/error.json, src/main/webapp/i18n/fr/error.json
Affichage dynamique de la rupture de stock lors de la modification de la quantité depuis le catalogue et depuis le panier
Débug d'un probleme du ticket de gestion de stock optimiste
=> Feature 116

src/main/webapp/app/components/products/display/products.component.html, src/main/webapp/app/components/products/display/products.component.ts, src/main/webapp/i18n/en/product.json, src/main/webapp/i18n/fr/product.json
Changement du titre une fois la recherche effectué (affichage de la quantité de produit affiché)
=> Feature 108

src/main/java/com/m2gi/ecom/repository/ProductRepository.java, src/main/java/com/m2gi/ecom/service/ProductService.java, src/main/java/com/m2gi/ecom/service/impl/ProductServiceImpl.java, src/main/java/com/m2gi/ecom/web/rest/ProductResource.java, src/main/webapp/app/components/products/display/products.component.html, src/main/webapp/app/components/products/display/products.component.ts, src/main/webapp/app/components/services/cart.service.ts, src/main/webapp/app/components/services/product.service.ts, src/main/webapp/app/components/services/promotion.service.ts, src/main/webapp/content/css/ecom.css
Amélioration lisibilité du code
Ajout du bouton de tri 
Ajout des paramètres sortBy et sortOrder pour l'api REST
Gestion du tri des promotions côté front
=> Feature 71

src/main/webapp/app/components/categories/display/categories.component.html, src/main/webapp/app/components/categories/display/categories.component.ts, src/main/webapp/app/components/products/display/products.component.html, src/main/webapp/app/components/products/display/products.component.ts, src/main/webapp/app/components/services/categories.service.ts
Déplacement de l'attribut **listCategory** de CategoriesComponent à CategoriesService pour pouvoir l'utiliser dans ProductsComponent afin d'afficher le nom de la catégorie.
=> feature-118: Renommage des titres des pages selon catégorie

src/main/java/com/m2gi/ecom/domain/UserDetails.java, src/main/java/com/m2gi/ecom/service/impl/UserService.java
-Création et suppression fonctionnelle via les panels de création de compte ou d'administration des comptes.
=> Feature 115: Création automatique du panier et UserDetails à la création d'un utilisateur.

src/main/java/com/m2gi/ecom/domain/Promotion.java, src/main/java/com/m2gi/ecom/repository/PromotionRepository.java, src/main/java/com/m2gi/ecom/service/PromotionService.java, src/main/java/com/m2gi/ecom/service/impl/PromotionServiceImpl.java, src/main/java/com/m2gi/ecom/web/rest/OrderResource.java, src/main/webapp/app/entities/cart/cart.model.ts
-Prise en compte des promotions dans le calcul du total de la commande dans le back.
-Correction d'un bug de calcul du total du panier dans le front. Le bug avait lieu quand un produit était en promotion, la quantité n'était pas prise en compte.
Signed-off-by: HAMICI Ryadh <hamiciryadh@gmail.com>
=> Feature 104: Prise en compte des promotions dans les commandes.

src/main/java/com/m2gi/ecom/domain/Promotion.java, src/main/java/com/m2gi/ecom/repository/PromotionRepository.java, src/main/java/com/m2gi/ecom/service/PromotionService.java, src/main/java/com/m2gi/ecom/service/impl/PromotionServiceImpl.java, src/main/java/com/m2gi/ecom/web/rest/OrderResource.java, src/main/webapp/app/components/payment/display/payment.component.ts, src/main/webapp/app/components/products/display/products.component.ts, src/main/webapp/app/components/services/cart.service.ts, src/main/webapp/app/components/services/promotion.service.ts, src/main/webapp/app/entities/cart/cart.model.ts
-Correction d'un bug qui faisait qu'au rafraichissement de toute page autre que la page d'accueil les promotions étaient perdues.
Signed-off-by: HAMICI Ryadh <hamiciryadh@gmail.com>
=> Feature 125: Perte des promotions lors du rafraichissement de la page.

src/main/java/com/m2gi/ecom/domain/Promotion.java, src/main/java/com/m2gi/ecom/domain/PromotionalCode.java, src/main/java/com/m2gi/ecom/repository/PromotionRepository.java, src/main/java/com/m2gi/ecom/service/PromotionService.java, src/main/java/com/m2gi/ecom/service/impl/PromotionServiceImpl.java, src/main/java/com/m2gi/ecom/web/rest/OrderResource.java, src/main/webapp/app/components/categories/display/categories.component.ts, src/main/webapp/app/components/payment/display/payment.component.ts, src/main/webapp/app/components/products/display/products.component.ts, src/main/webapp/app/components/services/cart.service.ts, src/main/webapp/app/components/services/promotion.service.ts, src/main/webapp/app/entities/cart/cart.model.ts, src/main/webapp/app/entities/promotion/update/promotion-update.component.html, src/main/webapp/app/entities/promotion/update/promotion-update.component.ts, src/main/webapp/app/entities/promotional-code/update/promotional-code-update.component.html, src/main/webapp/app/entities/promotional-code/update/promotional-code-update.component.ts
-Bloquer la modification des promotions sauf pour la date de fin. 
-Bloquer la modification des codes promos sauf pour la date de fin. 
-Correction d'un bug lors de la création/suppression de promotion. 
-Correction de warnings TS.
=> Feature 107: Bloquer la modifications des promos et codes promos sauf pour la date de fin.

src/main/resources/config/application-dev.yml, src/main/resources/config/application-prod.yml, src/main/resources/config/application.yml
-Association d'une adresse mail à l'application.
=> Feature 76: Mail de vérification pour la création de compte.

src/main/webapp/app/components/cart/display/cart.component.html, src/main/webapp/i18n/fr/cart.json
=> Feature 130

src/main/webapp/app/components/categories/display/categories.component.ts, src/main/webapp/app/components/products/display/products.component.ts, src/main/webapp/app/components/services/promotion.service.ts
Debug nom affiché lors du clique sur une categorie
=> Feature 131

src/main/java/com/m2gi/ecom/domain/Category.java
=> avancement filter avec bug

src/main/webapp/app/components/payment/display/payment.component.ts, src/main/webapp/app/components/reusableComponents/product-line/product-line.component.ts, src/main/webapp/app/entities/product/detail/product-detail.component.html, src/main/webapp/app/entities/product/detail/product-detail.component.ts, src/main/webapp/app/layouts/navbar/navbar.component.ts, src/main/webapp/app/shared/confirm-dialog/confirm-dialog.component.html, src/main/webapp/app/shared/confirm-dialog/confirm-dialog.component.ts, src/main/webapp/app/shared/shared.module.ts, src/main/webapp/content/css/ecom.css, src/main/webapp/i18n/en/global.json, src/main/webapp/i18n/fr/global.json
- Ajout de la possibilité d'ajouter un produit au panier depuis la fiche d'information produit + cacher les champs (tags ..) s'ils sont vides.
- Ajout d'un nouveau composant pour l'affichage de boites de dialogues de confirmation et utilisation pour la demande de déconnexion.
- Utilisation de la nouvelle boite de dialogue de confirmation lors du click sur le bouton de suppression d'un article du panier.
- Mise en forme du bouton d'ajout au panier dans le détail produit 
- Suppression des warnings
=> Feature ihm
